baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "tillac"
theme = "cayman-hugo-theme"

# Google analytics
googleAnalytics = "UA-123456789-1"

# Disqus comments
disqusShortname = "XXX"

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # Footer text, can be markdown
  footer = "Blablabla"

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex = true

  # Breakpoints
  large_breakpoint = "64em"
  medium_breakpoint = "42em"

  # Header colors
  header_heading_color = "#fff"
  header_background_color = "#741336"
  header_background_color_secondary = "#741336"

  # Text colors
  section_headings_color = "#741336"
  body_text_color = "#606c71"
  blockquote_text_color = "#819198"

  # Code colors
  code_background_color = "#f3f6fa"
  code_text_color = "#567482"

  # Border colors
  border_color = "#dce6f0"
  table_border_color = "#e9ebec"
  hr_border_color = "#eff0f1"

[menu]
  [[menu.nav]]
    name = "tillac"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "what we do"
    url = "/what/"
    weight = 3
  [[menu.nav]]
    name = "about"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "contact"
    url = "/contact/"
    weight = 5
