baseURL = "https://www.tillac-data.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "tillac"

# Google analytics
googleAnalytics = "UA-154610501-2"

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # Footer text, can be markdown
  footer_credits1 = "Photos : Copyright J. Vroylandt"
  footer_credits2 = "Theme : inspired by Cayman-Hugo-Theme"

  footer_contact1 = "tillac" 
  footer_contact2 = "9 quai de la Canardière" 
  footer_contact3 = "60500 CHANTILLY" 
  footer_contact4 = "FRANCE" 
  footer_contact5 = "<a href='mailto:contact@tillac-data.com'>contact@tillac-data.com</a>" 

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex = true

  # Breakpoints
  large_breakpoint = "64em"
  medium_breakpoint = "42em"

  # Header colors
  header_heading_color = "#fff"
  header_background_color = "#741336"
  header_background_color_secondary = "#741336"

  # Text colors
  section_headings_color = "#741336"
  body_text_color = "#606c71"
  blockquote_text_color = "#819198"

  # Code colors
  code_background_color = "#f3f6fa"
  code_text_color = "#567482"

  # Border colors
  border_color = "#dce6f0"
  table_border_color = "#e9ebec"
  hr_border_color = "#eff0f1"
  
  # social
  socialize = true
  
  [[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/tillac_data"

  [[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/tillac"
  
  [[params.social]]
  name = "Linkedin"
  icon = "linkedin"
  url = "https://www.linkedin.com/company/53487191/"

[menu]
  [[menu.nav]]
    name = "tillac"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "what we do"
    url = "/what"
    weight = 3
  [[menu.nav]]
    name = "about"
    url = "/about"
    weight = 4
  [[menu.nav]]
    name = "contact"
    url = "/contact"
    weight = 5



